image: node:6.2.0:slim

cache:
  paths:
  - node_modules/

stages:
  - test

run-test:
  stage: test
  script:
   - npm install
   - npm test
  tags:
    - docker

build:
  stage: test
  script:
   - npm install
   - npm run build
  tags:
    - docker